### ISSUE TITLE
Chart getting duplicated for every useEffect call in react app

### ISSUE THREAD

**Issue by jeyk333** [vasturiano/sunburst-chart#100] opened 2022-11-07 14:27 UTC
In my react, I am calling the chart method inside useEffect with data and also passing the data variable in the dependency array. Initially, its rendering properly. But, whenever, the data get updated, instead of the updating the chart, its creating new chart on every useEffect call. How can I solve this chart duplicating and instead of it, I need the chart to get updated.

````
import React, { useEffect, useRef, useState } from 'react'
import Sunburst from 'sunburst-chart'
import * as d3 from 'd3'

const SunburstChart = ({ data }) => {
  const color = d3.scaleOrdinal(d3.schemePaired)

  useEffect(() => {
      Sunburst()
        .data(data)
        .width(740)
        .height(740)
        .sort((a, b) => b.value - a.value)
        .color((d) => color(d.name))
        .excludeRoot(true)(document.getElementById('chart-sunburst'))
    }
  }, [data])

  return (
    <div id="chart-container">
      <div id="chart-sunburst"></div>
    </div>
  )
}

export default SunburstChart
````
![Screenshot 2022-11-09 at 10 39 30](https://user-images.githubusercontent.com/54062741/200743891-d54985c9-7449-4bb8-b475-1ba6c6ac37ec.png)

**Comment by jeyk333** [comment] 2022-11-09 05:10
@vasturiano Please let me, how to fix this one

**Comment by vasturiano** [comment] 2022-11-09 10:12
@jeyk333 thanks for reaching out.

This seems to be more of a question around React rather than this Sunburst component.
I can't advise specifically what should be the React pattern for you to use here, maybe a React forum would be more appropriate for that, but reinstantiating a Sunburst chart everytime the data changes (via `useEffect`) is certainly not right.
The chart should be instantiated only once within a single component's lifecycle.

You can also use [react-kapsule](https://github.com/vasturiano/react-kapsule) as it does all the wrapping for you out of the box.

**Comment by jeyk333** [comment] 2022-11-09 13:03
Ok, let me check with react-kapsule library

**Comment by jeyk333** [comment] 2022-11-09 16:07
@vasturiano I have tried using React-kapsule. But, the similar issue occurs here too.

```
import React, { useEffect, useRef, useState } from 'react'
import Sunburst from 'sunburst-chart'
import * as d3 from 'd3'

import fromKapsule from 'react-kapsule'

const ReactSunburst = fromKapsule(Sunburst, {
  methodNames: ['focusNode', 'onClick'],
})

const SunburstChart = ({ data, loading }) => {
  const chartRef = useRef(null)
  const color = d3.scaleOrdinal(d3.schemePaired)
  const [newData, setNewData] = useState(data)

  return (
    <div id="chart-sunburst" ref={chartRef}>
      <ReactSunburst
        width={740}
        sort={(a, b) => b.value - a.value}
        color={(d) => color(d.name)}
        label={(d) => (d.value ? `${d.name} - ${d.value}` : d.name)}
        height={740}
        excludeRoot
        data={newData}
      />
    </div>
  )
}

export default SunburstChart
```
![Screenshot 2022-11-09 at 21 36 10](https://user-images.githubusercontent.com/54062741/200880575-e0f2da7e-a578-4a61-8e16-9d999167b779.png)

Whenever, I tried to interact with the chart, this console error occurs and chart is not zooming

**Comment by vasturiano** [comment] 2022-11-09 22:59
@jeyk would you mind making an reproducing simple example on https://codesandbox.io/ ?

**Comment by jeyk333** [comment] 2022-11-10 06:28
sure

**Comment by SeaShackleton** [comment] 2023-08-12 15:15
In React v18 the duplicate is expected when using Strict Mode in development. It won't show up in production or if you remove Strict Mode.

Replace:
`  <React.StrictMode>
    <App />
  </React.StrictMode>`
With:
`  <>
    <App />
  </>`
and you'll see the duplicate no longer available.

**Comment by coreymunn3** [comment] 2024-06-05 21:26
For those of us who do not have the option of removing StrictMode, there is a better solution. Please see this [issue](https://github.com/vasturiano/sunburst-chart/issues/85) explanation for more on why this happens and how to implement specifically in a React app. 

You do not need to use Kapsule (and I would recommend against using it) Essentially what @jeyk333 needs to do here is add a cleanup function to his useEffect of
```
return () => {
      if (chartRef.current?.children[0]) {
        chartRef.current.removeChild(chartRef.current.children[0]);
      }
    };
```

and that should do the trick. 

@vasturiano This issue should probably now be marked as closed.

**Closed** 2024-06-23 10:12 UTC

**Comment by sundargautam18** [comment] 2025-06-20 10:41
You can fix this issue with **innerHtml** cleaner on **cleanup**

For example: 
```
 useEffect(() => {
    if ( !chartRef.current) return;

    const container = chartRef.current as HTMLElement;

    // Clear previous chart content
    container.innerHTML = "";
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    //@ts-ignore
    const myChart = Sunburst()
      .height(372)
      .width(300)
      .data({
        name: "root",
        children: [
          {
            name: "Vacant",
            tag: "vacant",
            value: 10
          },
          {
            name: "Occupied flats",
            tag: "packed",
            total: 12,
            children: [
              {
                name: "By owners",
                tag: "residentials",
                value: 6,
              },
              {
                name: "By tenants",
                tag: "non-residentials",
                value: 6
              },
            ],
          },
        ],
      })
      .excludeRoot(true)
      .label((d: { value: any; total: any; }) => `${d.value ?? d.total ?? 0}`)
      .tooltipContent((d: { value: any; name: any; total: any; }) =>
        d.value ? `${d.name}: ${d.value ?? 0}` : `${d.name}: ${d.total ?? 0}`
      )
      .strokeColor("")
      .color((d: { tag: any; }) => {
        switch (d.tag) {
          case "vacant":
            return "#EB6C00";
          case "packed":
            return "#34405F";
          case "residentials":
            return "#818FB5";
          case "non-residentials":
            return "#4C5D8B";
          default:
            return "#000000";
        }
      });

    // Mount chart
    myChart(container);

    // Cleanup function
    return () => {
      container.innerHTML = "";
    };
  }, [occupiedData]);
```
